spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  application:
    name: API-GATEWAY

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8079}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: READ_ONLY

server:
  port: 8080

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

